name: CI - Lint and Test

on:
  pull_request:
    branches:
        - '*'  # Trigger the workflow when a pull request targets in all branches

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the Python version required by project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run linter (e.g., Flake8 or Black)
      - name: Run linter
        run: |
          pip install flake8  # Install linter if not in requirements
          flake8 .  # Run linter on the current directory

      # Step 5: Run tests
      - name: Run tests
        run: |
          pytest  # Run the tests
