name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  EC2_HOST: 52.39.46.176
  EC2_USERNAME: ec2-user

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest

  deploy:
    name: Deploy to EC2
    needs: test
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem
        echo -e "Host ec2\n\tHostName ${{ env.EC2_HOST }}\n\tUser ${{ env.EC2_USERNAME }}\n\tIdentityFile ~/.ssh/ec2.pem\n\tStrictHostKeyChecking no" > ~/.ssh/config

    - name: Deploy to EC2
      run: |
        # Stop the existing service
        ssh ec2 'sudo systemctl stop fastapi-catalog'
        
        # Remove old deployment
        ssh ec2 'rm -rf ~/Backend-Master-Challenge'
        
        # Copy new files
        scp -r ./ ec2:~/Backend-Master-Challenge/
        
        # Install/update dependencies
        ssh ec2 'cd ~/Backend-Master-Challenge && pip3.11 install -r requirements.txt'
        
        # Start the service
        ssh ec2 'sudo systemctl start fastapi-catalog'
        
        # Check service status
        ssh ec2 'sudo systemctl status fastapi-catalog'
