name: FastAPI Catalog CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-west-2
  EC2_HOST: 52.39.46.176
  EC2_USERNAME: ec2-user

jobs:
  deploy:
    name: Deploy to EC2
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Setup SSH key
        mkdir -p ~/.ssh
        echo "$EC2_SSH_KEY" > ~/.ssh/key.pem
        chmod 600 ~/.ssh/key.pem
        
        # Copy files and restart service
        scp -i ~/.ssh/key.pem -o StrictHostKeyChecking=no -r ./* ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }}:~/Backend-Master-Challenge/
        ssh -i ~/.ssh/key.pem -o StrictHostKeyChecking=no ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }} "sudo systemctl restart fastapi-catalog"
